baseurl = "https://iliass.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Welcome"
  #logo = "img/avatar-icon.png"
  logo = "img/logo.png"
  #favicon = "img/favicon.ico"
  favicon = "img/logo.ico"
  dateFormat = "January 2, 0000"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Iliass TAHIRI"
  website = "iliass.netlify.com"
  email = "iliass.tahiri@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "IliassTAHIRI"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
  linkedin = "iliass-tahiri-69422679"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    identifier = "Pages"
    name = "Pages"
    weight = 2

[[menu.main]]
    parent = "Pages"
    name = "Gallery"
    url = "page/gallery/"
    weight = 1

[[menu.main]]
    parent = "Pages"
    name = "Publications"
    url = "page/publications"
    weight = 2


[[menu.main]]
    name = "CV"
    url = "page/cv/"
    weight = 3
